export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR";
export const RESET_WEATHER = "RESET_WEATHER";
export const SET_RESET_WEATHER = "SET_RESET_WEATHER";
