export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const RESET_WEATHER = 'RESET_WEATHER';
export const SET_RESET_WEATHER = 'SET_RESET_WEATHER';
export const TOOGLE_FAVORITE_WEATHER = 'TOOGLE_FAVORITE_WEATHER';
export const GET_FAVORITE_WEATHER = 'GET_FAVORITE_WEATHER';
export const ERROR_FAVORITE_WEATHER = 'ERROR_FAVORITE_WEATHER';
